version: "3.7"

services:
  ams-be:
    image: "ncc-erp-ams-be:latest"
    container_name: "ams-be-dev2"
    build:
      context: ./ncc-erp-ams/
      dockerfile: Dockerfile.php8.0
    ports:
      - "8000:8000"
    env_file:
      - ./envs/.env.prod.be
    restart: always

  ams-fe:
    image: "ncc-erp-ams-fe:latest"
    container_name: ams-fe-dev2
    build:
      context: ./ncc-erp-ams-fe
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    env_file:
      - ./envs/.env.prod.fe
    restart: always
